const petList = [
  {
    name: "Dog",
    aggressiveness: 4,
    love: 10,
    attentionNeeded: 9,
    lifespan: 8,
    intelligence: 9,
    imageUrl: "dog.jpeg",
  },
  {
    name: "Cat",
    aggressiveness: 3,
    love: 7,
    attentionNeeded: 5,
    lifespan: 9,
    intelligence: 7,
    imageUrl: "cat.jpeg",
  },
  {
    name: "Rabbit",
    aggressiveness: 2,
    love: 6,
    attentionNeeded: 6,
    lifespan: 5,
    intelligence: 5,
    imageUrl: "rabbit.jpeg",
  },
  {
    name: "Hamster",
    aggressiveness: 2,
    love: 5,
    attentionNeeded: 4,
    lifespan: 3,
    intelligence: 3,
    imageUrl: "hamster.jpeg",
  },
  {
    name: "Parrot",
    aggressiveness: 3,
    love: 8,
    attentionNeeded: 8,
    lifespan: 10,
    intelligence: 10,
    imageUrl: "parrot.jpeg",
  },
  {
    name: "Fish",
    aggressiveness: 1,
    love: 1,
    attentionNeeded: 1,
    lifespan: 3,
    intelligence: 1,
    imageUrl: "fish.jpeg",
  },
  {
    name: "Turtle",
    aggressiveness: 1,
    love: 3,
    attentionNeeded: 2,
    lifespan: 10,
    intelligence: 4,
    imageUrl: "turtle.jpeg",
  },
  {
    name: "Snake",
    aggressiveness: 3,
    love: 2,
    attentionNeeded: 2,
    lifespan: 8,
    intelligence: 4,
    imageUrl: "snake.jpeg",
  },
  {
    name: "Raymond Dong",
    aggressiveness: 1,
    love: 0,
    attentionNeeded: 100,
    lifespan: 1,
    intelligence: -5,
    imageUrl: "raymond.png",
  },
  {
    name: "Guinea Pig",
    aggressiveness: 1,
    love: 7,
    attentionNeeded: 6,
    lifespan: 4,
    intelligence: 5,
    imageUrl: "gpig.jpeg",
  },
  {
    name: "Ferret",
    aggressiveness: 4,
    love: 6,
    attentionNeeded: 7,
    lifespan: 6,
    intelligence: 8,
    imageUrl: "ferret.jpeg",
  },
];
export { petList };
