const petList = [
  {
    name: "Dog",
    Aggression: 4,
    Love: 10,
    Attention_Needed: 9,
    LifeSpan: 8,
    Intelligence: 9,
    imageUrl: "dog.jpg",
  },
  {
    name: "Cat",
    Aggression: 3,
    Love: 7,
    Attention_Needed: 5,
    LifeSpan: 9,
    Intelligence: 7,
    imageUrl: "cat.jpg",
  },
  {
    name: "Rabbit",
    Aggression: 2,
    Love: 6,
    Attention_Needed: 6,
    LifeSpan: 5,
    Intelligence: 5,
    imageUrl: "rabbit.jpg",
  },
  {
    name: "Hamster",
    Aggression: 2,
    Love: 5,
    Attention_Needed: 4,
    LifeSpan: 3,
    Intelligence: 3,
    imageUrl: "hamster.jpg",
  },
  {
    name: "Parrot",
    Aggression: 3,
    Love: 8,
    Attention_Needed: 8,
    LifeSpan: 10,
    Intelligence: 10,
    imageUrl: "parrot.jpg",
  },
  {
    name: "Fish",
    Aggression: 1,
    Love: 1,
    Attention_Needed: 1,
    LifeSpan: 3,
    Intelligence: 1,
    imageUrl: "fish.jpg",
  },
  {
    name: "Turtle",
    Aggression: 1,
    Love: 3,
    Attention_Needed: 2,
    LifeSpan: 10,
    Intelligence: 4,
    imageUrl: "turtle.jpg",
  },
  {
    name: "Snake",
    Aggression: 3,
    Love: 2,
    Attention_Needed: 2,
    LifeSpan: 8,
    Intelligence: 4,
    imageUrl: "snake.jpg",
  },
  {
    name: "Guinea Pig",
    Aggression: 1,
    Love: 7,
    Attention_Needed: 6,
    LifeSpan: 4,
    Intelligence: 5,
    imageUrl: "gpig.jpg",
  },
  {
    name: "Ferret",
    Aggression: 4,
    Love: 6,
    Attention_Needed: 7,
    LifeSpan: 6,
    Intelligence: 8,
    imageUrl: "ferret.jpg",
  },
];
export { petList };
